[package]
name = "bevy_billboard"
version = "0.1.0"
authors = ["Andrew Bentley <andrew@bentley.codes>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/atbentley/bevy_plugin_billboard"
readme = "README.md"

[dependencies]
bevy = "0.1.3"
